// Code generated by MockGen. DO NOT EDIT.
// Source: component.go
//
// Generated by this command:
//
//	mockgen -destination=mock.go -package=mock -source=component.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTestComponent is a mock of TestComponent interface.
type MockTestComponent struct {
	ctrl     *gomock.Controller
	recorder *MockTestComponentMockRecorder
	isgomock struct{}
}

// MockTestComponentMockRecorder is the mock recorder for MockTestComponent.
type MockTestComponentMockRecorder struct {
	mock *MockTestComponent
}

// NewMockTestComponent creates a new mock instance.
func NewMockTestComponent(ctrl *gomock.Controller) *MockTestComponent {
	mock := &MockTestComponent{ctrl: ctrl}
	mock.recorder = &MockTestComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestComponent) EXPECT() *MockTestComponentMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockTestComponent) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockTestComponentMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockTestComponent)(nil).Close), ctx)
}

// HealthCheck mocks base method.
func (m *MockTestComponent) HealthCheck(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockTestComponentMockRecorder) HealthCheck(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockTestComponent)(nil).HealthCheck), ctx)
}

// Init mocks base method.
func (m *MockTestComponent) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockTestComponentMockRecorder) Init(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockTestComponent)(nil).Init), ctx)
}

// Run mocks base method.
func (m *MockTestComponent) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockTestComponentMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockTestComponent)(nil).Run), ctx)
}
