#!/usr/bin/env bash
#
# Генерация Go-кода из OpenAPI спецификаций.
#
# Использование:
#   bash openapi-generate.sh <api-dir> <service-root>
#
# Для каждого YAML-файла в <api-dir> генерирует:
#   - internal/api/{name}/api.gen.go   — типы, интерфейсы, роутер (oapi-codegen)
#   - internal/handler/{name}/handler.go — структура хэндлера с заглушками (scaffold)
#   - internal/handler/{name}/register.go — функция регистрации на mux (scaffold)
#
# Дополнительно генерирует:
#   - {api-dir}/embed.gen.go                — go:embed для спецификаций
#   - internal/handler/register.gen.go  — агрегатор, вызывающий Register всех хэндлеров
#
# Переменные окружения:
#   CHECK=1  — не генерирует, а проверяет что файлы актуальны (для CI)
#
set -euo pipefail

API_DIR="${1:?Usage: $0 <api-dir> <service-root>}"
SERVICE_ROOT="${2:?Usage: $0 <api-dir> <service-root>}"

if [ ! -d "$API_DIR" ]; then
  echo "ERROR: API directory not found: $API_DIR" >&2
  exit 1
fi

cd "$SERVICE_ROOT" || exit 1

# Определяем module path из go.mod
MODULE_PATH="$(grep '^module ' go.mod | awk '{print $2}')"
if [ -z "$MODULE_PATH" ]; then
  echo "ERROR: could not determine module path from go.mod" >&2
  exit 1
fi

# Определяем версию platform-core из go.mod сервиса
PLATFORM_MODULE="easybnk.gitlab.yandexcloud.net/backend/platform-core"
PLATFORM_VERSION="$(grep "$PLATFORM_MODULE" go.mod | awk '{print $2}' | head -1)"
if [ -z "$PLATFORM_VERSION" ]; then
  echo "ERROR: $PLATFORM_MODULE not found in go.mod" >&2
  exit 1
fi

echo "==> Using platform-core ${PLATFORM_VERSION}..."

PLATFORM_PATH="$(go list -m -f '{{.Dir}}' "${PLATFORM_MODULE}" 2>/dev/null || true)"

# Скачиваем модуль
if [ -z "$PLATFORM_PATH" ]; then
  PLATFORM_PATH="$(
    go mod download -json "${PLATFORM_MODULE}@${PLATFORM_VERSION}" \
    | grep '"Dir"' \
    | awk -F'"' '{print $4}'
  )"
fi

if [ -z "$PLATFORM_PATH" ]; then
  echo "ERROR: failed to resolve platform-core path" >&2
  exit 1
fi

BASE_CONFIG="$PLATFORM_PATH/pkg/openapi/codegen/cfg.yaml"
if [ ! -f "$BASE_CONFIG" ]; then
  echo "ERROR: base oapi-codegen config not found: $BASE_CONFIG" >&2
  exit 1
fi

SCAFFOLD_CMD="${PLATFORM_MODULE}/cmd/openapi-scaffold@${PLATFORM_VERSION}"

# Вычисляем относительный путь к api-dir от корня сервиса
API_DIR_ABS="$(cd "$API_DIR" && pwd)"
SERVICE_ROOT_ABS="$(pwd)"
REL_API_DIR="${API_DIR_ABS#"$SERVICE_ROOT_ABS"/}"

# Сбор спецификаций
found_spec=0
SPEC_NAMES=()
EMBED_GLOBS=""

for SPEC in "$API_DIR"/*.yaml "$API_DIR"/*.yml; do
  [ -f "$SPEC" ] || continue
  found_spec=1

  FILENAME="$(basename "$SPEC")"
  EXT="${FILENAME##*.}"
  NAME="${FILENAME%.*}"
  SPEC_NAMES+=("$NAME")

  # Запоминаем расширения для go:embed
  if [[ "$EMBED_GLOBS" != *"*.${EXT}"* ]]; then
    EMBED_GLOBS="${EMBED_GLOBS:+$EMBED_GLOBS }*.${EXT}"
  fi

  OUTPUT="internal/api/${NAME}/api.gen.go"
  PACKAGE="$NAME"

  mkdir -p "$(dirname "$OUTPUT")"

  # Собираем конфиг для oapi-codegen
  TMPCONFIG="$(mktemp)"
  trap 'rm -f "$TMPCONFIG"' EXIT
  cat > "$TMPCONFIG" <<EOF
package: ${PACKAGE}
output: ${OUTPUT}
$(cat "$BASE_CONFIG")
EOF

  echo "==> Generating $OUTPUT from $SPEC..."
  go run "github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest" \
    --config="$TMPCONFIG" "$SPEC"

  rm -f "$TMPCONFIG"
  trap - EXIT

# Запускаем scaffold — локально через путь, на CI через модульный путь
if [ -d "$PLATFORM_PATH/cmd/openapi-scaffold" ]; then
  go run "$PLATFORM_PATH/cmd/openapi-scaffold" \
    --spec "$SPEC" \
    --gen-package "internal/api/${NAME}" \
    --handler-dir "internal/handler/${NAME}" \
    --service-root "$SERVICE_ROOT"
else
  go run "${SCAFFOLD_CMD}" \
    --spec "$SPEC" \
    --gen-package "internal/api/${NAME}" \
    --handler-dir "internal/handler/${NAME}" \
    --service-root "$SERVICE_ROOT"
fi
done

if [ "$found_spec" -eq 0 ]; then
  echo "ERROR: no OpenAPI specs found in $API_DIR" >&2
  exit 1
fi

# Генерация api/embed.gen.go
EMBED_FILE="${REL_API_DIR}/embed.gen.go"
EMBED_PKG="$(basename "$REL_API_DIR")"
echo "==> Generating $EMBED_FILE..."

cat > "$EMBED_FILE" <<GOEOF
// Code generated by openapi-generate.sh. DO NOT EDIT.
package ${EMBED_PKG}

import "embed"

//go:embed ${EMBED_GLOBS}
var specFS embed.FS

// FS возвращает файловую систему с OpenAPI спецификациями.
func FS() embed.FS {
	return specFS
}
GOEOF

# Генерация internal/handler/register.gen.go
REGISTER_DIR="internal/handler"
REGISTER_FILE="${REGISTER_DIR}/register.gen.go"
mkdir -p "$REGISTER_DIR"
echo "==> Generating $REGISTER_FILE..."

{
  echo "// Code generated by openapi-generate.sh. DO NOT EDIT."
  echo "package handler"
  echo ""
  echo "import ("
  echo "	\"context\""
  echo "	\"net/http\""
  echo ""
  for NAME in "${SPEC_NAMES[@]}"; do
    echo "	\"${MODULE_PATH}/internal/handler/${NAME}\""
  done
  echo ")"
  echo ""
  echo "// Register регистрирует обработчики всех OpenAPI спецификаций на общий mux."
  echo "func Register(ctx context.Context, mux *http.ServeMux) {"
  for NAME in "${SPEC_NAMES[@]}"; do
    echo "	${NAME}.Register(ctx, mux)"
  done
  echo "}"
} > "$REGISTER_FILE"

# CI CHECK
if [ "${CHECK:-0}" = "1" ]; then
  if ! git diff --quiet --exit-code \
      "$EMBED_FILE" \
      "$REGISTER_FILE" \
      internal/api/ \
      internal/handler/; then
    echo "ERROR: generated files are stale. Run 'make generate' and commit." >&2
    git diff --stat
    exit 1
  fi
  echo "==> CHECK passed: all generated files are up to date."
fi

# Форматирование
go fmt "$EMBED_FILE" "$REGISTER_FILE" >/dev/null 2>&1 || true

echo "==> Done. Generated code for specs: ${SPEC_NAMES[*]}"